---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Anna Preenu Pappachan Rosily github:preenuann"
date: "21/09/2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r}
library("Lahman")
library("tidyverse")
```

```{r load-pkg-data}
#| message: false
```

## Exercises

### Exercise 1

```{r glimpse-data}

dplyr::glimpse(Teams)

```

The `Teams` dataset has 3015 observations and 48 variables.

```{r}
help(Teams)

```

### Exercise 2

```{r}
mets <- Teams  |>
  dplyr::filter(teamID == "NYN")
my_mets <- mets |> 
  dplyr::filter(yearID>=2004 & yearID<=2012)
my_mets |> 
  dplyr::select(W,L,yearID,G)
```

### Exercise 3

```{r}
mets_ben <- Teams |>
  dplyr::select(yearID, G, teamID,R, RA, W, L) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben
```


```{r}
dplyr::glimpse(mets_ben)
```

```{r}
mets_ben <- mets_ben |>
  dplyr::rename(RS= R)    # new name = old name
mets_ben
```

### Exercise 4

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(WPct = (1/(1+((RA/RS)^2))),WinPct = W/G,)
mets_ben

```

       

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(W_hat =WPct*G)
mets_ben
```

...

### Exercise 5

```{r}

# Adding a field to identify if the team performed better or worse than expected
mets_ben <- mets_ben |>
 dplyr:: mutate(Performance = ifelse(W > W_hat, "Better", "Worse"))

mets_ben

```

```{r}
library(dplyr)

summary_stats <- mets_ben |>
  group_by(Performance) |>
  summarize(count = n())

print(summary_stats)

```

### Exercise 6

```{r}
# Finding the teams best performance during Ben's time
best_seasons <- dplyr::arrange(mets_ben, desc(W))
best_seasons

```

...

### Exercise 7

```{r}
# Ranking of the team's peformance wrt our model
mets_ben <-mets_ben |>
  dplyr::mutate(Diff = W -W_hat) |>
  dplyr::arrange(desc(Diff))


```

```{r}
View(mets_ben)
```

...

### Exercise 8

```{r}
# Summary of the team's performance
mets_ben |>
  dplyr::summarize(
    num_years = n(), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct =mean(WPct), 
    sum_resid = sum(Diff)
  )
```

...

### Exercise 9

```{r}

```

...

### Exercise 10


```{r}
library(dplyr)
mets_ben <- mets_ben %>% 
  dplyr::mutate(gm = ifelse(yearID == 2004,"Jim Duquette", 
         ifelse(yearID >= 2005 & yearID <= 2010,"Omar Minaya","Sandy Alderson"
         )))
print(mets_ben)
```

###Excercise 11

```{r Group by the manager (gm) variable and summarize the data}
 
manager_summary <- mets_ben %>%
  group_by(gm) %>%
  dplyr::summarize(
    num_years = n(),
    total_W = sum(W),
    total_L = sum(L),
    total_WPct = mean(WPct),
    sum_resid = sum(Diff)
  )

# Print the manager summary
manager_summary
```
